### ISSUE TITLE
1.20 incompatibility? (Unsure)

### ISSUE THREAD

**Issue by DarkChromaMC** [stonar96/RayTraceAntiXray#8]
When running a fresh install of RayTraceAntiXray I get console spammed with this message:
```
[15:35:23 WARN]: [RayTraceAntiXray] Task #9 for RayTraceAntiXray v1.10.8 generated an exception
java.lang.NullPointerException: Cannot invoke "com.vanillage.raytraceantixray.data.PlayerData.getLocations()" because "playerData" is null
	at com.vanillage.raytraceantixray.tasks.UpdateBukkitRunnable.lambda$run$0(UpdateBukkitRunnable.java:36) ~[raytraceantixray-1.10.8.jar:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1092) ~[?:?]
	at com.vanillage.raytraceantixray.tasks.UpdateBukkitRunnable.run(UpdateBukkitRunnable.java:34) ~[raytraceantixray-1.10.8.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.jar:git-Purpur-1990]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.20.jar:git-Purpur-1990]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1507) ~[purpur-1.20.jar:git-Purpur-1990]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:484) ~[purpur-1.20.jar:git-Purpur-1990]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1421) ~[purpur-1.20.jar:git-Purpur-1990]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1192) ~[purpur-1.20.jar:git-Purpur-1990]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.jar:git-Purpur-1990]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
	```

**Comment by stonar96** [comment]
Yes, I'm aware.
